apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  distribution:
    version: "2.9.x"
    registry: ghcr.io/fluxcd
  sync:
    kind: GitRepository
    url: https://github.com/shuu01/flux.git
    ref: refs/heads/main
    path: clusters/staging
    provider: github
    pullSecret: flux-gitops
